# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'MQTT Client Sample WS'

target 'MQTT Client Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTT Client Sample
  # AzureIoTuAmqp and AzureIoTuMqtt are dependencies of AzureIoTHubClient and must be
  # included when using development pods. 
  # For published pods, AzureIoTuAmqp may be omitted.
  pod 'AzureIoTUtility'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTuMqtt'
  pod 'AzureIoTHubClient'
end
